### ISSUE TITLE
ABL Status Bar icon states cannot be easily distiguished by those with color-blindness

### ISSUE THREAD

**Issue by mattatobin** [Pale-Moon-Addons-Team/adblock-latitude#14]
Just what it says on the tin.

Target: 3.0.3 and 3.5.0b2

**Comment by wolfbeast** [comment]
Potentially easy fix: make the grey much lighter and invert the ABL text to be a darker grey instead of white.

**Comment by michgagnon** [comment]
Someone commented on the difficulty to see the icon on a dark background. I don't think it would be a problem if you make it solid. I.e. very light grey, with dark grey "ABL", but no transparency whatsoever. On the other hand, if you make it partially transparent, people will have problems with some themes. Although I think you should push first and foremost for something good with the standard theme, it should also be visible for those who use a high-contrast setting because people who use them typically do so because they have vision problems. 

Showing well in many other themes is gravy, I think.

**Comment by wolfbeast** [comment]
This is not about the ease to see it on different backgrounds, it is about the luminance similarity between red and grey versions of the icons which makes it very difficult for people with R/G color-blindness to see the state of the extension.

**Comment by wolfbeast** [comment]
![abl16x16grey2-ncb](https://cloud.githubusercontent.com/assets/3359132/10267640/0e9803ae-6a9c-11e5-9cda-690e62b2cb2c.png)

Suggested version of the updated color for 16x16
