### ISSUE TITLE
This website detects Adblock Latitude

### ISSUE THREAD

**Issue by KNTRO** [Pale-Moon-Addons-Team/adblock-latitude#16]
Hi there,

[This website](http://radiosonline.biz/) detects use of Adblock Latitude and don't let me browse its content, unless I let this domain unblocked.

Could you do something in order to bypass this, please?

Thanx in advance. :wink:

**Comment by mattatobin** [comment]
The problem is the html that is being generated to block you doesn't have a unique ID.. Likely also by design. You might be able to write a couple of filters for it but it may break other parts of the site.

May just have to give in an disable ABL for that site only. But this is VERY aggressive.. Perhaps the site just isn't worth your time if you don't want to unblock ads for it.

**Comment by KNTRO** [comment]
> Perhaps the site just isn't worth your time if you don't want to unblock ads for it.

Ha! I don't even use this site, just reporting this issue because the site was very aggressive —you're right— with the adblock stuff.

I just hope not to find this sick behavior with sites I really care of… :worried:

Closin' issue.
