### ISSUE TITLE
Loading of blocked content on PM start

### ISSUE THREAD

**Issue by nelegalno** [Pale-Moon-Addons-Team/adblock-latitude#17]
Since ABL v3.0.2 if you have enabled "***Show my windows and tabs from last time***" the blocked content is ignored when you start PM and *unwanted content is loaded/executed/displayed*. I'd like to know if any work was done to fix that problem in the v3.5.0b1 branch and if not why and do you intend to?

**P.S.** I've been using the *please_kill_startup_performance* since it was first added and still haven't seen any problems despite the one quoted as reason for it's removal.

**P.P.S.** I'd also like to know the team stance on ***Adblock Latitude has also been configured to allow some non-intrusive advertising*** in the v3.5.0b1 and why some of the changes from v3.0.3.1 have been reverted in the v3.5.0b1?

**Comment by mattatobin** [comment]
One.. That pref was only introduced in 3.0.1 and had to be backed out due to issues.

Two.. ABL has no such functionality the only way you would have exceptions for "non-intrusive advertising" is if you previously had the filter enabled in ABP when you migrated over.. However, in ABL it would show like any other filter list. Approved Ads was only ever a filterlist that via some internal code was given absolute precedence and priority over all other filters.. This functionality was removed upon our first ever released version of ABL. So if you previously had it in Adblock Plus or manually sought out and added the filterlist your self it would show up.. But only as just another filterlist.

Three... The beta is out of date as compared to the currently supported released version (currently 3.0.3.1).. While I have brought the recent additions from the 3.0.x versions over to 3.5 I have not yet released an updated beta which is kind of been in a bit of a holding pattern until some things got sorted out.

AS FOR THE MAIN ISSUE for which this bug is titled. This is a complete WONTFIX for 3.0.x versions. 3.5 sidesteps the issue entirely because it is a fully xul toolkit-based extension.. NOT bootstrap.

So I am closing this bug as WONTFIX.
